plugins: initial support of parallel execution (#58)
* add support for plugins, export some internal code, add plugin sample

* fix docs in exported code

* modify plugin runner to execute plugins independently in parallel

* clean up usage doc whitespace

* re-organize code, update release script, add better error message handling from plugins

* update circle config

* fix gitignore and revert circle config changes

* pull plugin runner into own file, modify sample, add plugin test

* revert test proto file change

* add plugin samples and use in circle tests

* update circle config to add debug detail

* prefer explicit return from goroutine and send on done chan

* override pipefail in plugin ci tests

* update README with --plugins option in usage

* revert uppercasing in json tag for Protolock type, add other json tags

* use different plugin name for error sample

* add json tags to Data and include example nodejs plugin

* run ci test on nodejs plugin

* update README with details and wiki link to plugin docs

* remove console log demo and add note in nodejs plugin example

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,9 @@ version: 2
 jobs:
   build:
     docker:
-      - image: circleci/golang:1.10
+      - image: circleci/golang:1.11
+        environment:
+          GO111MODULE: "on"
 
     working_directory: /go/src/github.com/nilslice/protolock
     steps:
@@ -18,3 +20,64 @@ jobs:
       - run: cat proto.lock | grep "testdata:/:test.proto"
       - run: protolock status
       - run: protolock commit
+      - run: protolock status --plugins=_not-a-plugin_ | grep "executable file not found"
+      - run: 
+          name: check output using plugin-sample-error
+          command: |
+            set +o pipefail
+
+            protolock status --plugins=plugin-sample-error | grep "some error"
+      - run:
+          name: check output using plugin-sample
+          command: |
+            set +o pipefail
+
+            WARNINGS=$(protolock status --plugins=plugin-sample | wc -l)
+            if [ "$WARNINGS" != 2 ]; then
+              exit 1
+            fi
+      - run: 
+          name: check output using multiple plugins, with one error expected
+          command: |
+            set +o pipefail
+
+            protolock status --plugins=plugin-sample,plugin-sample-error | grep "some error"
+            protolock status --plugins=plugin-sample-error,plugin-sample | grep "some error"
+      - run: 
+          name: check output using multiple plugins with errors
+          command: |
+            set +o pipefail
+
+            ERRS=$(protolock status --plugins=plugin-sample-error,plugin-sample-error | grep "some error" | wc -l)
+            if [ "$ERRS" != 2 ]; then
+              exit 1
+            fi
+            MOREERRS=$(protolock status --plugins=plugin-sample-error,plugin-sample-error,plugin-sample-error | grep "some error" | wc -l)
+            if [ "$MOREERRS" != 3 ]; then
+              exit 1
+            fi
+            
+  plugin_nodejs:
+    docker:
+      - image: circleci/node:8
+
+    steps: 
+      - checkout
+      # fetch depenencies, test code
+      - run: npm i --prefix plugin-samples/plugin-sample-js/
+      - run: npm run pack --prefix plugin-samples/plugin-sample-js/
+      - run: 
+          name: 
+          command: |
+            set +o pipefail
+            cd plugin-samples/plugin-sample-js/
+            WARNINGS=$(cat example.data.json | ./plugin-sample-js)
+            echo $WARNINGS | grep '{"filepath":"path/to/file.proto","message":"Something bad happened."}'
+            echo $WARNINGS | grep '{"filepath":"path/to/another.proto","message":"Something else bad happened."}'
+
+workflows:
+  version: 2
+  build-cmd-test-plugins:
+    jobs:
+      - build
+      - plugin_nodejs
