add plugin samples and use in circle tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,3 +18,37 @@ jobs:
       - run: cat proto.lock | grep "testdata:/:test.proto"
       - run: protolock status
       - run: protolock commit
+      - run:
+          name: check output using plugin-sample
+          command: |
+            WARNINGS=$(protolock status --plugins=plugin-sample | wc -l)
+            if [ "$WARNINGS" -ne 2 ]; then
+              exit 1
+            fi
+
+      - run: 
+          name: check output using plugin-sample-error
+          command: |
+            protolock status --plugins=plugin-sample-error | grep "some error"
+
+      - run: 
+          name: check output using multiple plugins, with one error expected
+          command: |
+            ERR=$(protolock status --plugins=plugin-sample,plugin-sample-error)
+            echo $ERR | grep "some error"
+            REV=$(protolock status --plugins=plugin-sample-error,plugin-sample)
+            echo $REV | grep "some error"
+      
+      - run: 
+          name: check output using multiple plugins with errors
+          command: |
+            ERRS=$(protolock status --plugins=plugin-sample-error,plugin-sample-error | grep "some error" | wc -l)
+            if [ "$ERRS" -ne 2 ]; then
+              exit 1
+            fi
+            MOREERRS=$(protolock status --plugins=plugin-sample-error,plugin-sample-error,plugin-sample-error | grep "some error" | wc -l)
+            if [ "$ERRS" -ne 3 ]; then
+              exit 1
+            fi
+
+
